apps/views/Admin_Discuss.py
from flask import request, render_template, Blueprint
from createdb import DiscussTable, ReplyTable, db

Blu_AdminDiscuss = Blueprint('Blu_AdminDiscuss', __name__)

global ShrinkStatus
ShrinkStatus = 0
@Blu_AdminDiscuss.route('/Admin_Discuss')
def Admin_Discuss():
    ShrinkS = request.args.get('Shrinkstatus')
    DisID = request.args.get('DisID')
    DiscussID = request.args.get('DiscussID')
    RepleyID = request.args.get('RepleyID')
    print(ShrinkS)
    print(DisID)
    if ShrinkS == None:
        ShrinkS = '1'
    if DisID == None:
        DisID = '1'
    DisID = int(DisID)
    global ShrinkStatus
    ShrinkStatus = int(ShrinkS)

    if ShrinkStatus == 0:
        ShrinkStatus = 1
    else:
        ShrinkStatus = 0
    print(ShrinkStatus)


    if DiscussID != None:
        DiscussID = int(DiscussID)
        DeleteDiscussList(DiscussID)
    if RepleyID != None:
        RepleyID = int(RepleyID)
        DeleteReplayList(RepleyID)
    DiscussList = DiscussTable.query.all()

    return render_template('Admin_Discuss.html',
                           HTML_DiscussList=DiscussList,
                           ShrinkStatus=ShrinkStatus,
                           DisID=DisID)

def DeleteDiscussList(id):
    repList = ReplyTable.query.filter_by(DiscussID=id)
    for re in repList:
        db.session.delete(re)
        db.session.commit()
    dis = DiscussTable.query.get(id)
    db.session.delete(dis)
    db.session.commit()

def DeleteReplayList(id):
    re = ReplyTable.query.get(id)
    db.session.delete(re)
    db.session.commit()

apps/views/Admin_Knowledge.py
from flask import request, render_template, Blueprint
from createdb import ChapterListTable, KnowledgeListTable, db
from apps import oprate_sql
Blu_AdminKnowledge = Blueprint('Blu_AdminKnowledge', __name__)

@Blu_AdminKnowledge.route('/Admin_Knowledge', methods=['POST', 'GET'])
def Admin_Knowledge():
    OptionType = request.args.get('OptionType')
    if OptionType == None:
        OptionType = '1'
    OptionType = int(OptionType)
    if OptionType == 2:
        KnowID = request.args.get('KnowID')
        KnowID = int(KnowID)
        HTML = ChapterListUpdate(KnowID)
    elif OptionType == 3:
        KnowID = request.args.get('KnowID')
        KnowID = int(KnowID)
        ChapterDelete(KnowID)
        HTML = ChapterDisplayInfo()
    elif OptionType == 4:
        KnowID = request.args.get('KnowID')
        KnowID = int(KnowID)
        HTML = KnowledgeListUpdate(KnowID)
    elif OptionType == 5:
        KnowID = request.args.get('KnowID')
        KnowID = int(KnowID)
        KnowledgeDelete(KnowID)
        HTML = ChapterDisplayInfo()
    else:
        HTML = ChapterDisplayInfo()
    return HTML

def ChapterDisplayInfo():
    if request.method == 'POST':
        InputType = request.form.get('Type')
        if InputType == 'Chapter':
            FirstNum = request.form.get('FirstNum')
            Firstname = request.form.get('Firstname')
            SecondNum = request.form.get('SecondNum')
            Secondname = request.form.get('Secondname')
            oprate_sql.ChapterListAdd(FirstNum, Firstname, SecondNum, Secondname)
        elif InputType == 'Knowledge':
            Iexaplem = request.form.get('Iexaplem')
            Isolution = request.form.get('Isolution')
            Ichapterid = request.form.get('Ichapterid')
            oprate_sql.KnowledgeListAdd(Iexaplem, Isolution, Ichapterid)
    ChapterList = ChapterListTable.query.all()
    KnowledgeList = KnowledgeListTable.query.all()
    return render_template('Admin_Knowledge.html',
                           ChapterList=ChapterList,
                           KnowledgeList=KnowledgeList,
                           OptionType=1)

def ChapterDelete(id):
    ChaList = ChapterListTable.query.get(id)
    for kno in ChaList.Know:
        db.session.delete(kno)
        db.session.commit()
    for pro in ChaList.ChaPro:
        db.session.delete(pro)
        db.session.commit()
    db.session.delete(ChaList)
    db.session.commit()

def KnowledgeDelete(id):
    Know = KnowledgeListTable.query.get(id)
    db.session.delete(Know)
    db.session.commit()

def ChapterListUpdate(id):
    if request.method == 'POST':
        ChaID = request.form.get('ID')
        Fname = request.form.get('Fname')
        Sname = request.form.get('Sname')
        oprate_sql.ChapterListUpdate(id, Fname, Sname)
    ChapterList = ChapterListTable.query.get(id)
    return render_template('Admin_Knowledge.html',
                           ChapterList=ChapterList,
                           OptionType=2)

def KnowledgeListUpdate(id):
    if request.method == 'POST':
        ID = request.form.get('ID')
        Example = request.form.get('Example')
        Solution = request.form.get('Solution')
        ChaID = request.form.get('ChaID')
        oprate_sql.KnowledgeListUpdate(id, Example, Solution, ChaID)
    KnowledgeList = KnowledgeListTable.query.get(id)
    return render_template('Admin_Knowledge.html',
                           KnowledgeList=KnowledgeList,
                           OptionType=3)

apps/views/Admin_Practice.py
from flask import request, render_template, Blueprint
from createdb import ProblemListTable, ChapterListTable, db
from apps import oprate_sql
Blu_AdminPractice = Blueprint('Blu_AdminPractice', __name__)
@Blu_AdminPractice.route('/Admin_Practice', methods=['POST', 'GET'])
def Admin_Practice():
    DeleteID = request.args.get('DeleteID')
    OptionType = request.args.get('OptionType')
    ModifyID = request.args.get('ModifyID')
    if OptionType == None:
        OptionType='1'
    OptionType = int(OptionType)
    if OptionType != 2:
        HTML = DisplayPracticeInfo(DeleteID)
    elif OptionType == 2:
        HTML = ModifyPracticeInfo(ModifyID)
    return HTML

def DisplayPracticeInfo(DeleteID):
    if DeleteID != None:
        DeleteID = int(DeleteID)
        de = ProblemListTable.query.get(DeleteID)
        db.session.delete(de)
        db.session.commit()
    ProList = ProblemListTable.query.all()
    if request.method == 'POST':
        FirstDire = request.form.get('FirstDire')
        SecondDire = request.form.get('SecondDire')
        Content = request.form.get('Content')
        Detail = request.form.get('Detail')
        Answer = request.form.get('Answer')
        Type = request.form.get('Type')
        Option = request.form.get('Option')
        print(Answer)
        CharList = ChapterListTable.query.all()
        if (FirstDire != None) and (SecondDire != None) and (Content != None) and (Detail != None) and (Answer != None):
            for cha in CharList:
                if (cha.FisrtDirectory == int(FirstDire)) and (cha.SecondDirectory == int(SecondDire)):
                    print(FirstDire)
                    oprate_sql.ProblemListAdd(Content, Detail, Answer, cha.id, Type, Option)
    return render_template('Admin_Practice.html',
                           PublishList=ProList,
                           OptionType=1)
def ModifyPracticeInfo(id):
    ModifyID = int(id)

    pra = ProblemListTable.query.get(id)
    print(pra)
    if request.method == 'POST':
        Id = request.form.get('Id')
        Type = request.form.get('Type')
        Option = request.form.get('Option')
        Answer = request.form.get('Answer')
        AnswerDes = request.form.get('AnswerDes')
        Content = request.form.get('Content')
        oprate_sql.ProblemListUpdate(ModifyID, Type, Option, Answer, AnswerDes, Content)
    return render_template('Admin_Practice.html',
                           PublishList=pra,
                           OptionType=2)

apps/views/Admin_Quizzes.py
from flask import request, render_template, Blueprint
from createdb import db, QuizzesListTable, QuizzesQuestionListTable

Blu_AdminQuizzes = Blueprint('Blu_AdminQuizzes', __name__)

@Blu_AdminQuizzes.route('/Admin_Quizzes', methods=['GET', 'POST'])
def Admin_Quizzes():
    OptionType = request.args.get('OptionType')
    if OptionType == None:
        OptionType = '1'
    OptionType = int(OptionType)
    if OptionType != 2:
        HTML = AdminQuizzesDisplay()
    else:
        HTML = AdminQuizzesModify()
    return HTML

def AdminQuizzesDisplay():
    QuizzesID = request.args.get('QuizzesID')
    if QuizzesID != None:
        QuizzesID = int(QuizzesID)
        Qui = QuizzesQuestionListTable.query.get(QuizzesID)
        db.session.delete(Qui)
        db.session.commit()
    if request.method == 'POST':
        print('asdfsdfs')
        Rcontent = request.form.get('Rcontent')
        Ranswer = request.form.get('Ranswer')
        Rlevel = request.form.get('Rlevel')
        Rlevel = int(Rlevel)
        if(Rlevel<=3):
            QuizzesAdd(Rcontent, Ranswer, Rlevel)
    ProblemList = QuizzesQuestionListTable.query.all()
    return render_template('Admin_Quizzes.html',
                           ProblemList=ProblemList,
                           OptionType=1)

def AdminQuizzesModify():
    QuizzesID = request.args.get('QuizzesID')
    QuizzesID = int(QuizzesID)
    ProblemList = QuizzesQuestionListTable.query.get(QuizzesID)

    if request.method == 'POST':
        Qcontent = request.form.get('Qcontent')
        Qanswer = request.form.get('Qanswer')
        Qlevel = request.form.get('Qlevel')

        ProblemList.Content = Qcontent
        ProblemList.Answer = Qanswer
        ProblemList.Quizzes = int(Qlevel)
        print(Qlevel)
        db.session.commit()
    return render_template('Admin_Quizzes.html',
                           ProblemList=ProblemList,
                           OptionType=2)

def QuizzesAdd(content, answer, level):
    Flag = 0
    QuiList = QuizzesQuestionListTable.query.all()
    for qui in QuiList:
        if qui.Content == content:
            Flag = 1
            break
    if Flag == 0:
        Qui = QuizzesQuestionListTable(Content=content, Answer=answer, Quizzes=level)
        db.session.add(Qui)
        db.session.commit()

apps/views/Admin_UserDefine.py
from flask import request, render_template, Blueprint, redirect
from apps.createdb import UserDataInfoTable, UserPublishListTable, ChapterListTable, db
from apps import DataType, oprate_sql

Blu_AdminUserDefine = Blueprint('Blu_AdminUserDefine', __name__)

@Blu_AdminUserDefine.route('/Admin_UserDfine', methods=['GET', 'POST'])
def Admin_UserDfine():
    uid = DataType.GetUserInfo().id
    uid = str(uid)
    uid = int(uid)
    userInfo = oprate_sql.UserInfoCheckForID(uid)
    UserDataList = UserDataInfoTable.query.filter_by(UserID=uid)
    for us in UserDataList:
        UserDataInfo = us

    OptionType = request.args.get('OptionType')
    if OptionType == None:
        OptionType = '1'
    OptionType = int(OptionType)
    if OptionType != 2:
        HTML = PostQuestionDisplay(userInfo, UserDataInfo)
    else:
        HTML = ModifyPostQuestion(userInfo, UserDataInfo)
    return HTML

def PostQuestionDisplay(userInfo, UserDataInfo):
    PubId = request.args.get('PublishID')
    if PubId != None:
        PubId = int(PubId)
        print(PubId)
        PubList = UserPublishListTable.query.get(PubId)
        print(PubList.Content)
        db.session.delete(PubList)
        db.session.commit()
        '''
        CharList = ChapterListTable.query.all()
        for cha in CharList:
            if (cha.FisrtDirectory == PubList.FisrtDirectory) and (cha.SecondDirectory == PubList.SecondDirectory):
                oprate_sql.ProblemListAdd(PubList.Content, PubList.AnswerDes, PubList.Answer, cha.id)
                #oprate_sql.UserPublishListDelete(PubId)
        '''
    Publish = UserPublishListTable.query.all()
    if request.method == 'POST':
        FirstDire = request.form.get('FirstDire')
        SecondDire = request.form.get('SecondDire')
        Content = request.form.get('Content')
        Detail = request.form.get('Detail')
        Answer = request.form.get('Answer')
        print(Answer)
        CharList = ChapterListTable.query.all()
        if(FirstDire != None) and (SecondDire != None) and (Content != None) and (Detail != None) and (Answer != None):
            for cha in CharList:
                if (cha.FisrtDirectory == int(FirstDire)) and (cha.SecondDirectory == int(SecondDire)):
                    print(FirstDire)
                    oprate_sql.ProblemListAdd(Content, Detail, Answer, cha.id)
    return render_template('Admin_UserDefine.html',
                           UserInfo=userInfo,
                           UserDataInfo=UserDataInfo,
                           PublishList=Publish,
                           OptionType=1)

def ModifyPostQuestion(userInfo, UserDataInfo):
    PubId = request.args.get('PublishID')
    PubId = int(PubId)

    if request.method == 'POST':
        PubList = UserPublishListTable.query.get(PubId)
        Pcontent = request.form.get('Pcontent')
        Pdetail = request.form.get('Pdetail')
        Panswer = request.form.get('Panswer')

        PubList.Content = Pcontent
        PubList.AnswerDes = Pdetail
        PubList.Answer = Panswer
        db.session.commit()
    PubList = UserPublishListTable.query.get(PubId)

    return render_template('Admin_UserDefine.html',
                           UserInfo=userInfo,
                           UserDataInfo=UserDataInfo,
                           PublishList=PubList,
                           OptionType=2)

apps/views/Admin_user.py
from flask import render_template, Blueprint, request
from createdb import UserInfoTable, UserDataInfoTable, db, ErrorListTable, DiscussTable, ReplyTable
from flask_sqlalchemy import SQLAlchemy
from apps import oprate_sql

Blu_AdminUser = Blueprint('Blu_AdminUser', __name__)

@Blu_AdminUser.route('/Admin_user', methods=['POST', 'GET'])
def Admin_user():
    Option = request.args.get("OptionType")
    UserID = request.args.get("User_id")
    if (Option == None):
       HTML = OptionDisplay()
    elif int(Option) == 3:
        OptionDelete(UserID)
        HTML = OptionDisplay()
    elif int(Option) == 2:
        HTML = OptionModify(UserID)
    return HTML


def OptionDisplay():
    UserList = UserInfoTable.query.all()
    print(UserList)
    return render_template('Admin_user.html',
                           UserList=UserList,
                           OptionType=1)

def OptionDelete(uID):
    UserData = UserDataInfoTable.query.all()
    uID = int(uID)
    for ud in UserData:
        if ud.UserID == int(uID):
            db.session.delete(ud)
            db.session.commit()

    ErrList = ErrorListTable.query.filter_by(UserID=uID)
    for err in ErrList:
        db.session.delete(err)
        db.session.commit()

    ReplyList = ReplyTable.query.filter_by(ReUserID=uID)
    for re in ReplyList:
        db.session.delete(re)
        db.session.commit()

    DisList = DiscussTable.query.filter_by(userID=uID)
    for dis in DisList:
        db.session.delete(dis)
        db.session.commit()
    UserInfo = UserInfoTable.query.get(int(uID))
    db.session.delete(UserInfo)
    db.session.commit()

def OptionModify(uID):
    uID = int(uID)

    UserInfo = UserInfoTable.query.get(uID)
    print(UserInfo)
    if request.method == 'POST':
        print('Submit')
        name = request.form.get('Name')
        pwd = request.form.get('Pwd')
        email = request.form.get('Email')
        print(name)
        print(pwd)
        print(email)
        oprate_sql.UserInfoUpdate(uID, name, pwd, email, UserInfo.photo)
    return render_template('Admin_user.html',
                           UserInfo=UserInfo,
                           OptionType=2)

apps/views/Discuss.py
from flask import Blueprint, request, render_template, redirect
from apps.createdb import DiscussTable, ReplyTable, UserDataInfoTable
from apps import DataType
from apps import oprate_sql

Blu_Discuss = Blueprint('Blu_Discuss', __name__)
global ReplayId
ReplayId = 0

@Blu_Discuss.route('/Discuss', methods=['POST', 'GET'])
def Discuss():
    Singout = request.args.get('Singout')
    ReplayID = request.args.get('ReplayID')
    if ReplayID != None:
        ReplayID = int(ReplayID)
    global ReplayId
    if ReplayId == ReplayID:
        ReplayId = 0
    else:
        ReplayId = ReplayID
    if Singout != None:
        if int(Singout) == 1:
            DataType.ClearUserInfo()
    uid = DataType.GetUserInfo().id
    uid = str(uid)
    if (len(uid) == 0):
        return redirect('/Login')
    uid = int(uid)
    userInfo = oprate_sql.UserInfoCheckForID(uid)
    UserDataList = UserDataInfoTable.query.filter_by(UserID=uid)
    for us in UserDataList:
        UserDataInfo = us
    pubcontent = request.args.get("PubContent")
    replycotent = request.args.get("ReplyContent")
    disID = request.args.get("Submit")
    LikesUserID = request.args.get("LikesResid")
    uid = int(uid)
    if (replycotent != None) and (len(replycotent) != 0):
        if(disID != None) and (len(disID) != 0):
            disID = int(disID)
            oprate_sql.ReplyListAdd(disID, replycotent, uid)
    if (pubcontent != None) and (len(pubcontent) != 0):
        oprate_sql.DiscussListAdd(pubcontent, uid)
    DiscussList = DiscussTable.query.all()
    if LikesUserID != None:
        LikesUserID = int(LikesUserID)
        if LikesUserID != uid:
            oprate_sql.UserDataUpdate(LikesUserID, 'Likes', 1)
    return render_template('Discuss.html',
                           HTML_DiscussList=DiscussList,
                           UserInfo=userInfo,
                           UserDataInfo=UserDataInfo,
                           RankStatus=DataType.GetRankStatus(),
                           RankValue=DataType.GetRmarkValue(),
                           ReplayID=ReplayId)

apps/views/UserPractice.py
from flask import render_template, request, Blueprint

Blu_UserPractice = Blueprint('Blu_UserPractice', __name__)

@Blu_UserPractice.route('/UserPractice', methods=['POST', 'GET'])
def UserPractice():
    render_template('UserPractice.html')

apps/templates/Admin_Knowledge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="./static/css/Admin_Knowledge.css">
    <title>知识点管理</title>
</head>
<body>
    {% if OptionType == 1 %}
    <div class="UserInfo">
        <h2>Chapter List</h2>
        <table width=80% border='1'>
                <tr>
                    <th>ID</th>
                    <th>Chapter</th>
                    <th>First Level Directory</th>
                    <th>Second Level Directory</th>
                    <th>Modify</th>
                    <th>Delete</th>
                </tr>
                {% for cha in ChapterList %}
                    <tr>
                        <td class="ID">{{ cha.id }}</td>
                        <td class="ChapterName">{{ cha.FisrtDirectory }}.{{ cha.SecondDirectory }}</td>
                        <td class="ChapterF">{{ cha.FirstDirectoryName }}</td>
                        <td class="ChapterS">{{ cha.SecondDirectoryName }}</td>
                        <td class="Modify1"><a href="/Admin_Knowledge?KnowID={{ cha.id }}&&OptionType=2">Modify</a></td>
                        <td class="Delete"><a href="/Admin_Knowledge?KnowID={{ cha.id }}&&OptionType=3">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
        <h2>Example List</h2>
        <table width=80% border='1'>
                <tr>
                    <th>ID</th>
                    <th>Example</th>
                    <th>Solution</th>
                    <th>Chapter ID</th>
                    <th>Modify</th>
                    <th>Delete</th>
                </tr>
                {% for kno in KnowledgeList %}
                    <tr>
                        <td class="ID">{{ kno.id }}</td>
                        <td class="Example">{{ kno.Example }}</td>
                        <td class="Solution">{{ kno.Solution }}</td>
                        <td class="ChaID">{{ kno.ChaID }}</td>
                        <td class="Modify1"><a href="/Admin_Knowledge?KnowID={{ kno.id }}&&OptionType=4">Modify</a></td>
                        <td class="Delete"><a href="/Admin_Knowledge?KnowID={{ kno.id }}&&OptionType=5">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
    </div>
    <div class="ChapterAdd">
        <h2>Add Chapter</h2>
        <form method="post">
            <p>Type:</p>
            <input type="text" name="Type" readonly="readonly" required="required" value="Chapter">
            <p>First Level Directory:</p>
            <input type="text" placeholder="" name="FirstNum" required="required">
            <p>Name of First Level Directory:</p>
            <input type="text" placeholder="" name="Firstname" required="required">
            <p>Second Level Directory:</p>
            <input type="text" placeholder="" name="SecondNum" required="required">
            <p>Name of Second Level Directory:</p>
            <input type="text" placeholder="" name="Secondname" required="required">
            <button type="submit" value="Submit">Submit</button>
        </form>
        <h2>Add Example</h2>
        <form method="post">
            <p>Type:</p>
            <input type="text" name="Type" readonly="readonly" required="required" value="Knowledge">
            <p>Example:</p>
            <input type="text" placeholder="" name="Iexaplem" required="required">
            <p>Solution:</p>
            <input type="text" placeholder="" name="Isolution" required="required">
            <p>Chapte ID:</p>
            <input type="text" placeholder="" name="Ichapterid" required="required">
            <button type="submit" value="Submit">Submit</button>
        </form>
    </div>
    {% elif OptionType == 2 %}
        <div class="Modify">
            <h2>Modify Chapter Data</h2>
            <a href="{{ url_for('Blu_AdminKnowledge.Admin_Knowledge') }}">Back</a>
            <form method="post">
                <p>Chapter ID:</p>
                <input type="text" placeholder="" name="ID" required="required" value="{{ ChapterList.id }}">
                <p>First Level Directory:</p>
                <input type="text" placeholder="" name="Fname" required="required" value="{{ ChapterList.FirstDirectoryName }}">
                <p>Second Level Directory:</p>
                <input type="text" placeholder="" name="Sname" required="required" value="{{ ChapterList.SecondDirectoryName }}">
                <button type="submit" value="Submit">Submit</button>
            </form>
        </div>
    {% elif OptionType == 3 %}
        <div class="Modify">
            <h2>Modify Example Data</h2>
            <a href="{{ url_for('Blu_AdminKnowledge.Admin_Knowledge') }}">Back</a>
            <form method="post">
                <p>Example ID:</p>
                <input type="text" placeholder="" name="ID" required="required" value="{{ KnowledgeList.id }}">
                <p>Example:</p>
                <input type="text" placeholder="" name="Example" required="required" value="{{ KnowledgeList.Example }}">
                <p>Solution:</p>
                <input type="text" placeholder="" name="Solution" required="required" value="{{ KnowledgeList.Solution }}">
                <p>Associated Chapter ID:</p>
                <input type="text" placeholder="" name="ChaID" required="required" value="{{ KnowledgeList.ChaID }}">
                <button type="submit" value="Submit">Submit</button>
            </form>
        </div>
    {% endif %}
</body>
</html>

apps/templates/Admin_Quizzes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="./static/css/Admin_Quizzes.css">
    <title>Quizzes</title>
</head>
<body>
    {% if OptionType != 2 %}
    <div class="QuizzesInfo">
        <h2>Quizzes List</h2>
        <table width=80% border='1'>
                <tr>
                    <th>ID</th>
                    <th>Content</th>
                    <th>Answer</th>
                    <th>Level</th>
                    <th>Modify</th>
                    <th>Delete</th>
                </tr>
                {% for pro in ProblemList %}
                    <tr>
                        <td class="ID">{{ pro.id }}</td>
                        <td class="QContent">{{ pro.Content }}</td>
                        <td class="QAnswer">{{ pro.Answer }}</td>
                        <td class="QLevel">{{ pro.Quizzes }}</td>
                        <td class="Modify1"><a href="/Admin_Quizzes?QuizzesID={{ pro.id }}&&OptionType=2">Modify</a></td>
                        <td class="Delete"><a href="/Admin_Quizzes?QuizzesID={{ pro.id }}&&OptionType=1">Delete</a></td>
                    </tr>
                {% endfor %}
            </table>
            <div>
                <h2>Add Quizzes</h2>
                <form method ="post">
                    <p>Content:</p>
                    <input type="text" placeholder="Input Question" name="Rcontent" required="required">
                    <p>Answer:</p>
                    <input type="text" placeholder="Input Answer" name="Ranswer" required="required">
                    <p>Level:</p>
                    <input type="text" placeholder="Input Level" name="Rlevel" required="required">
                    <button type="submit" value="Submit">Submit</button>
                </form>
            </div>
    </div>
    {% else %}
        <div class="Modify">
            <h2>Modify Quizzes Data</h2>
            <a href="{{ url_for('Blu_AdminQuizzes.Admin_Quizzes') }}">Back</a>
            <form method="post">
                <p>Content:</p>
                <input type="text" placeholder="{{ ProblemList.Content }}" name="Qcontent" required="required" value="{{ ProblemList.Content }}">
                <p>Answer:</p>
                <input type="text" placeholder="{{ ProblemList.Answer }}" name="Qanswer" required="required" value="{{ ProblemList.Answer }}">
                <p>Level:</p>
                <input type="text" placeholder="{{ ProblemList.Quizzes }}" name="Qlevel" required="required" value="{{ ProblemList.Quizzes }}">
                <button type="submit" value="Submit">Submit</button>
            </form>
        </div>
    {% endif %}
</body>
</html>

apps/templates/Administration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="./static/css/Administration.css">
    <title>Administration</title>
</head>
<body>
    <div class="OnePage">
        <h2>Welcome to the Teacher's Classroom</h2>
        <a href="{{ url_for('Blu_user.Home') }}">Logout</a>
    </div>
    <div class="ListOption">
        <ul>
            <li>
                <a href="/Administration?OptionID=1">Student Management</a>
            </li>
            <li>
                <a href="/Administration?OptionID=2">Knowledge Base Management</a>
            </li>
            <li>
                <a href="/Administration?OptionID=3">Practice Management</a>
            </li>
            <li>
                <a href="/Administration?OptionID=4">Discussion Management</a>
            </li>
            <li>
                <a href="/Administration?OptionID=6">Quizzes Management</a>
            </li>
            <li>
                <a href="/Administration?OptionID=5">Post Questions Management</a>
            </li>
        </ul>
    </div>
    <div class="OptionPage">
        {% if OptionID == 1 %}
            <iframe src={{url_for('Blu_AdminUser.Admin_user')}}>
            </iframe>
        {% elif OptionID == 2 %}
            <iframe src="{{ url_for('Blu_AdminKnowledge.Admin_Knowledge') }}">

            </iframe>
        {% elif OptionID == 3 %}
            <iframe src="{{ url_for('Blu_AdminPractice.Admin_Practice') }}">

            </iframe>
        {% elif OptionID == 4 %}
            <iframe src="{{ url_for('Blu_AdminDiscuss.Admin_Discuss') }}">

            </iframe>
        {% elif OptionID == 5 %}
            <iframe src={{url_for('Blu_AdminUserDefine.Admin_UserDfine')}}>
            </iframe>
         {% elif OptionID == 6 %}
            <iframe src={{url_for('Blu_AdminQuizzes.Admin_Quizzes')}}>
            </iframe>
        {% endif %}
    </div>
</body>
</html>